### ISSUE TITLE
Error while trying to fetch the experts

### ISSUE THREAD

**Issue by coder-rakeshpaul** [microsoft/MoCapAct#17]
Hi I seem to be running into some authentication error while trying to get the expert clips using 
`python -m mocapact.download_dataset -t experts -c CMU_009_12 -d ./data`

the error that I get is 
```

Downloading experts dataset from: https://mocapact.blob.core.windows.net/public?sv=2020-10-02&si=public-1819108CAA5&sr=c&sig=Jw1zsVs%2BK2G6QP%2Bo%2FFPQb1rSUY8AL%2F24k4zhQuw5WPo%3D to ./data
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/rakesh/Desktop/project/MoCapAct/mocapact/download_dataset.py", line 107, in <module>
    download_dataset_from_url(DATASET_URL, blob_prefix, local_dest_path=args.dest_path, clips=expanded_clips)
  File "/home/rakesh/Desktop/project/MoCapAct/mocapact/download_dataset.py", line 25, in download_dataset_from_url
    for blob in expert_blobs:
  File "/home/rakesh/anaconda3/envs/monet/lib/python3.11/site-packages/azure/core/paging.py", line 123, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rakesh/anaconda3/envs/monet/lib/python3.11/site-packages/azure/core/paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rakesh/anaconda3/envs/monet/lib/python3.11/site-packages/azure/storage/blob/_list_blobs_helper.py", line 79, in _get_next_cb
    process_storage_error(error)
  File "/home/rakesh/anaconda3/envs/monet/lib/python3.11/site-packages/azure/storage/blob/_shared/response_handlers.py", line 177, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:6447f222-401e-001e-15fb-990a08000000
Time:2024-04-29T06:09:40.8774697Z
ErrorCode:AuthenticationFailed
authenticationerrordetail:Signature did not match. String to sign used was 


/blob/mocapact/public
public-1819108CAA5


2020-10-02
c






Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:6447f222-401e-001e-15fb-990a08000000
Time:2024-04-29T06:09:40.8774697Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was 


/blob/mocapact/public
public-1819108CAA5


2020-10-02
c





</AuthenticationErrorDetail></Error>


```

I am not sure what is the issue here, about a month ago I had managed to fetch the clips using the same command not sure why it's not working now. 

Thank you

**Comment by mynsng** [comment]
I encountered the same error. Could you suggest a possible solution?

**Comment by nolanwagener** [comment]
Hi all, sorry for the late response.

The Python script is no longer functional for security reasons.

As part of our shift to Hugging Face, we include some example experts [here](https://huggingface.co/microsoft/mocapact-models/tree/main/sample), which hopefully allows prospective users to play with the experts before downloading the whole dataset.
